title: BlankSlate
url: http://844196.com/blog
author: '844196'
description: いや、そういう声もあるというだけです
timezone: Asia/Tokyo

github:
    root: https://github.com
    repo: 844196/blog
    branch: gh-pages

exclude:
    - README.md
    - vendor
    - Guardfile
    - Gemfile
    - Gemfile.lock
baseurl: '/blog'
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "page:num"
gems:
    - jemoji
    - jekyll-sitemap
    - jekyll-paginate

markdown: redcarpet
redcarpet:
    extensions:
        - tables
        - fenced_code_blocks
        - no_intra_emphasis
        - strikethrough
        - footnotes
        - autolink
        - lax_spacing
        - space_after_headers
        - hard_wrap
        - highlight
        - with_toc_data

pygment: false
sass:
    style: compressed

disqus: 'blankslate844196'
